on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fail if generated CSS is different to committed CSS
        run: npm ci && npm exec gulp && git diff --exit-code
      - name: Run prettier on all CSS, HTML, JavaScript and JSON files
        run: >-
          npm exec --yes prettier -- --check
          '**.css'
          '**.html'
          '**.js'
          '**.json'
      - name: Run prettier on all Markdown files
        run: >-
          npm exec --yes prettier -- --check --prose-wrap=always
          '**.md'
      - name: Check the renovate configuration
        run: npm exec --yes --package renovate -- renovate-config-validator
      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
      - name: Run Pelican
        run: >-
          uv tool run --with-requirements=requirements.txt
          pelican --fatal=warnings
      - run: uv tool run yamllint .github
      - run: uv tool run reuse lint
# .github/workflows/check.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
