on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fail if generated CSS is different to committed CSS
        run: npm ci && npm exec gulp && git diff --exit-code
      - name: Run prettier on all CSS, HTML, JavaScript and JSON
        run: >-
          npm exec --yes prettier -- --check
          '**.css'
          '**.html'
          '**.js'
          '**.json'
      - name: Check the renovate configuration
        run: npm exec --yes --package renovate -- renovate-config-validator
      - name: Install uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6
      - name: Run Pelican
        run: >-
          uv tool run --with-requirements=requirements.txt
          pelican --fatal=warnings
      - name: Run yamllint on workflows
        run: >-
          uv tool run
          yamllint -c .github/yamllint-config-file -f github .github/workflows
