on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with: { node-version-file: package.json }
      - run: npm install --global "npm@$(jq -r .engines.npm package.json)"
      - run: npm version && npm ci && npm exec gulp && git diff --exit-code
      - run: >-
          npm exec --yes prettier -- --check
          '**.css'
          '**.html'
          '**.js'
          '**.json'
          '**.md'
      - run: npm exec --yes --package renovate -- renovate-config-validator
      - uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7
      - run: >-
          uv tool run --with-requirements=requirements.txt pelican
          --fatal=warnings
      - run: uv tool run yamllint .github
      - run: uv tool run reuse lint
# .github/workflows/check.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
