on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Run prettier on all CSS, HTML, JavaScript and JSON
        run: >-
          npm exec --yes prettier -- --check
          '**.css'
          '**.html'
          '**.js'
          '**.json'
      - name: Fail if generated CSS isn't committed
        run: npm ci && npm exec gulp && git diff --exit-code
      - name: Install uv
        uses: astral-sh/setup-uv@c9aa747934b6867b18bf8f6624a8929c4f76147b # v3
        with: { version: "0.4.18" }
      - name: Run Pelican
        run: >-
          uv tool run --with-requirements=requirements.txt
          pelican --fatal=warnings
