on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Fail if generated CSS is different to committed CSS
        run: npm ci && npm exec gulp && git diff --exit-code
      - name: Run prettier on all CSS, HTML, JavaScript and JSON
        run: >-
          npm exec --yes prettier -- --check
          '**.css'
          '**.html'
          '**.js'
          '**.json'
      - name: Check the renovate configuration
        run: npm exec --yes --package renovate -- renovate-config-validator
      - name: Install uv
        uses: astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086 # v3
        with: { version: "0.4.18" }
      - name: Run Pelican
        run: >-
          uv tool run --with-requirements=requirements.txt
          pelican --fatal=warnings
