on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  deploy:
    # yamllint disable-line rule:line-length
    uses: getpelican/pelican/.github/workflows/github_pages.yml@69e24fa82f0b6103930d85de5eeb8234414e6a11 # 4.11.0
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: pelicanconf.py
      requirements: --requirement requirements.txt
# .github/workflows/publish.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
