on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  deploy:
    uses: getpelican/pelican/.github/workflows/github_pages.yml@b86383fb28a160eeaf3e13cbf99469a0ed4cfcb2 # 4.10.1
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: pelicanconf.py
      requirements: --requirement requirements.txt
